package sop_corba;


/**
* sop_corba/ClienteInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* martes 24 de mayo de 2016 21H48' COT
*/

public interface ClienteInt extends ClienteIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ClienteInt
